/**
 * Capability hub — discovery, dependency, extension resolution (browser-safe).
 */

export type {
  ActionOverrideEntry,
  CapabilityDependency,
  CapabilityManifest,
  CapabilityProvides,
  CapabilityRequires,
  CapabilitySearchOptions,
  CompatCapability,
  CompatIssue,
  CompatibilityIssue,
  ComputeEffectiveTrustInput,
  CoreCompatibilityResult,
  EnforceCoreCompatibilityOptions,
  EntityExtensionEntry,
  EntityOverrideEntry,
  ExtensionResolver,
  MetadataCompatibility,
  RegistryEntry,
  RegistrySearchOptions,
  ResolutionConflict,
  RuleOverrideEntry,
  TrustLevel,
  ValidationResult,
} from "../../capability";
export {
  buildActionChain,
  CapabilityHub,
  CapabilityHubError,
  checkCoreCompatibility,
  checkTrustPermissions,
  clampTrust,
  computeEffectiveTrust,
  coreVersionRangeOf,
  createCapabilityHub,
  createExtensionResolver,
  createLocalRegistry,
  enforceCoreCompatibility,
  filterEntityByCapabilities,
  inferTrustLevel,
  LocalCapabilityRegistry,
  normalizeMinVersion,
  satisfiesVersionRange,
} from "../../capability";
