/**
 * Deployment runtime — health checks, graceful shutdown, environment,
 * deploy webhooks, blue-green instance switching (server-only).
 */

export {
  type AggregatedHealthStatus,
  type BlueGreenConfig,
  BlueGreenDeployer,
  type BuildConfig,
  type BuildPhase,
  type BuildResult,
  createCacheCheck,
  createDatabaseCheck,
  createEntityCheck,
  createEventBusCheck,
  DeployBuilder,
  type DeployEvent,
  type DeployPhase,
  type DeployResult,
  type DeployWebhookConfig,
  DeployWebhookHandler,
  detectEnvironment,
  type EnvironmentConfig,
  type EnvironmentFeatureFlags,
  type EnvironmentName,
  type ExecResult,
  GracefulShutdownManager,
  type GracefulShutdownManagerOptions,
  type HealthCheckFn,
  HealthCheckRegistry,
  type HealthCheckRegistryOptions,
  type HealthCheckResult,
  type HealthStatus,
  type HttpFetcher,
  livenessCheck,
  type NginxReloader,
  type ProcessExecutor,
  type ProcessHandle,
  type ProcessLauncher,
  type ShutdownHook,
  type ShutdownPhase,
  type ShutdownStatus,
  validateRequiredEnvVars,
  type WebhookHandleResult,
} from "../../deployment";
