/**
 * Deployment runtime — health checks, graceful shutdown, environment,
 * deploy webhooks, blue-green instance switching (server-only).
 */

export {
  type AggregatedHealthStatus,
  type BlueGreenConfig,
  BlueGreenDeployer,
  createCacheCheck,
  createDatabaseCheck,
  createEntityCheck,
  createEventBusCheck,
  type DeployArtifact,
  type DeployEvent,
  type DeployPhase,
  type DeployResult,
  type DeployWebhookConfig,
  DeployWebhookHandler,
  detectEnvironment,
  type EnvironmentConfig,
  type EnvironmentFeatureFlags,
  type EnvironmentName,
  GracefulShutdownManager,
  type GracefulShutdownManagerOptions,
  type HealthCheckFn,
  HealthCheckRegistry,
  type HealthCheckRegistryOptions,
  type HealthCheckResult,
  type HealthStatus,
  type HttpFetcher,
  livenessCheck,
  type NginxReloader,
  type NodeDeployClient,
  type NodeDeployStatus,
  type NodePhase,
  type ProcessHandle,
  type ProcessLauncher,
  RollingUpdateCoordinator,
  type RollingUpdateCoordinatorConfig,
  type RollingUpdatePhase,
  type RollingUpdateResult,
  type RollingUpdateRollbackResult,
  type ShutdownHook,
  type ShutdownPhase,
  type ShutdownStatus,
  validateRequiredEnvVars,
  type WebhookHandleResult,
} from "../../deployment";
