/**
 * Drizzle schema definition for system tables
 *
 * Exports all static system table definitions.
 * Used by .linchkit/drizzle-schema.generated.ts (which also includes
 * capability tables generated by linch CLI).
 */

export { fieldOverlaysTable, overlayStatusEnum } from "./overlay-table";
export {
  approvalStatusEnum,
  approvalsTable,
  eventStatusEnum,
  eventsTable,
  executionStatusEnum,
  executionsTable,
  overrideTargetTypeEnum,
  tenantOverridesTable,
} from "./system-tables";
