/*************************************************************************************************

Welcome to Baml! To use this generated code, please run one of the following:

$ npm install @boundaryml/baml
$ yarn add @boundaryml/baml
$ pnpm add @boundaryml/baml

*************************************************************************************************/

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ npm install @boundaryml/baml
//
/* eslint-disable */
// tslint:disable
// @ts-nocheck
// biome-ignore format: autogenerated code

import type { Audio, BamlCtxManager, BamlRuntime, ClientRegistry, Collector, Image, Pdf, Video } from "@boundaryml/baml"
import { toBamlError } from "@boundaryml/baml";
import type { partial_types } from "./partial_types";
import type TypeBuilder from "./type_builder";
import type * as types from "./types";
import type { Check, Checked, IntentAlternative, IntentResolution } from "./types";

export class LlmResponseParser {
  constructor(
    private runtime: BamlRuntime,
    private ctxManager: BamlCtxManager,
  ) {}

  ResolveIntent(
    llmResponse: string,
    __baml_options__?: {
      tb?: TypeBuilder;
      clientRegistry?: ClientRegistry;
      env?: Record<string, string | undefined>;
    },
  ): types.IntentResolution {
    try {
      const __rawEnv__ = __baml_options__?.env
        ? { ...process.env, ...__baml_options__.env }
        : { ...process.env };
      const __env__: Record<string, string> = Object.fromEntries(
        Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [
          string,
          string,
        ][],
      );
      return this.runtime.parseLlmResponse(
        "ResolveIntent",
        llmResponse,
        false,
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        __env__,
      ) as types.IntentResolution;
    } catch (error) {
      throw toBamlError(error);
    }
  }
}

export class LlmStreamParser {
  constructor(
    private runtime: BamlRuntime,
    private ctxManager: BamlCtxManager,
  ) {}

  ResolveIntent(
    llmResponse: string,
    __baml_options__?: {
      tb?: TypeBuilder;
      clientRegistry?: ClientRegistry;
      env?: Record<string, string | undefined>;
    },
  ): partial_types.IntentResolution {
    try {
      const __rawEnv__ = __baml_options__?.env
        ? { ...process.env, ...__baml_options__.env }
        : { ...process.env };
      const __env__: Record<string, string> = Object.fromEntries(
        Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [
          string,
          string,
        ][],
      );
      return this.runtime.parseLlmResponse(
        "ResolveIntent",
        llmResponse,
        true,
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        __env__,
      ) as partial_types.IntentResolution;
    } catch (error) {
      throw toBamlError(error);
    }
  }
}
