/**
 * Schema-to-GraphQL generator
 *
 * Converts a LinchKit SchemaDefinition into GraphQL object and input types
 * for use in a GraphQL API layer. Supports link-based relation resolvers.
 */

import type {
  ActionDefinition,
  Actor,
  DataProvider,
  FieldDefinition,
  LinkDefinition,
  Logger,
  MaskRecordOptions,
  PermissionGroupDefinition,
  SchemaDefinition,
  StateDefinition,
} from "@linchkit/core";
import { resolveTranslatableValue } from "@linchkit/core";
import { consoleLogger, maskRecord } from "@linchkit/core/server";
import {
  GraphQLBoolean,
  GraphQLEnumType,
  GraphQLFloat,
  GraphQLID,
  type GraphQLInputFieldConfig,
  GraphQLInputObjectType,
  type GraphQLInputType,
  GraphQLInt,
  GraphQLList,
  GraphQLNonNull,
  GraphQLObjectType,
  type GraphQLOutputType,
  GraphQLString,
} from "graphql";

// Cache for reusing GraphQLEnumType instances across output and input types
const enumTypeCache = new Map<string, GraphQLEnumType>();

/**
 * Sanitize a value string into a valid GraphQL enum value name.
 * GraphQL enum values must match /^[_A-Za-z][_0-9A-Za-z]*$/.
 */
function sanitizeEnumValue(value: string): string {
  // Replace non-alphanumeric/underscore characters with underscores
  let sanitized = value.replace(/[^_0-9A-Za-z]/g, "_");
  // Ensure it starts with a letter or underscore
  if (!/^[_A-Za-z]/.test(sanitized)) {
    sanitized = `_${sanitized}`;
  }
  return sanitized;
}

/**
 * Build or retrieve a cached GraphQLEnumType for an enum field with options.
 */
function getEnumTypeForField(
  schema: SchemaDefinition,
  fieldName: string,
  options: Array<{ value: string; label?: string }>,
): GraphQLEnumType {
  const enumName = `${toPascalCase(schema.name)}${toPascalCase(fieldName)}Enum`;
  const cached = enumTypeCache.get(enumName);
  if (cached) return cached;

  const enumType = new GraphQLEnumType({
    name: enumName,
    values: Object.fromEntries(
      options.map((o) => [sanitizeEnumValue(o.value), { value: o.value, description: o.label }]),
    ),
  });
  enumTypeCache.set(enumName, enumType);
  return enumType;
}

/**
 * Build or retrieve a cached GraphQLEnumType for a state field from a StateDefinition.
 */
function getEnumTypeForState(
  schema: SchemaDefinition,
  fieldName: string,
  stateDef: StateDefinition,
): GraphQLEnumType {
  const enumName = `${toPascalCase(schema.name)}${toPascalCase(fieldName)}State`;
  const cached = enumTypeCache.get(enumName);
  if (cached) return cached;

  const meta = stateDef.meta ?? {};
  const enumType = new GraphQLEnumType({
    name: enumName,
    values: Object.fromEntries(
      stateDef.states.map((s) => [
        sanitizeEnumValue(s),
        { value: s, description: (meta as Record<string, { label?: string }>)[s]?.label },
      ]),
    ),
  });
  enumTypeCache.set(enumName, enumType);
  return enumType;
}

/** Map of state machine name → StateDefinition, used to resolve state fields */
type StateMachineMap = Map<string, StateDefinition>;

/**
 * Map a LinchKit field type to a GraphQL output type.
 * Generates GraphQLEnumType for enum fields with options and state fields with known machines.
 */
function mapFieldToGraphQLType(
  field: FieldDefinition,
  fieldName: string,
  schema: SchemaDefinition,
  stateMachines?: StateMachineMap,
): GraphQLOutputType | null {
  switch (field.type) {
    case "string":
    case "text":
    case "date":
    case "datetime":
      return GraphQLString;
    case "enum": {
      if (field.options?.length) {
        return getEnumTypeForField(schema, fieldName, field.options);
      }
      return GraphQLString;
    }
    case "state": {
      const machineKey = field.machine;
      const machine = machineKey ? stateMachines?.get(machineKey) : undefined;
      if (machine?.states?.length) {
        return getEnumTypeForState(schema, fieldName, machine);
      }
      return GraphQLString;
    }
    case "number":
      return GraphQLFloat;
    case "boolean":
      return GraphQLBoolean;
    case "json":
      // JSON fields are represented as String (serialized JSON)
      return GraphQLString;
    default:
      return null;
  }
}

/**
 * Map a LinchKit field type to a GraphQL input type.
 * Reuses the same cached enum types generated by mapFieldToGraphQLType.
 *
 * For translatable fields, the input type is always GraphQLString.
 * Clients pass either a plain string (single-locale shortcut) or a JSON-encoded
 * locale map (e.g., '{"en":"Hello","zh-CN":"你好"}').
 */
export function mapFieldToGraphQLInputType(
  field: FieldDefinition,
  fieldName?: string,
  schema?: SchemaDefinition,
  stateMachines?: StateMachineMap,
): GraphQLInputType | null {
  // Translatable fields accept String input (plain string or JSON-encoded locale map)
  if (field.translatable) {
    return GraphQLString;
  }

  switch (field.type) {
    case "string":
    case "text":
    case "date":
    case "datetime":
      return GraphQLString;
    case "enum": {
      if (schema && fieldName && field.options?.length) {
        return getEnumTypeForField(schema, fieldName, field.options);
      }
      return GraphQLString;
    }
    case "state": {
      if (schema && fieldName) {
        const machineKey = field.machine;
        const machine = machineKey ? stateMachines?.get(machineKey) : undefined;
        if (machine?.states?.length) {
          return getEnumTypeForState(schema, fieldName, machine);
        }
      }
      return GraphQLString;
    }
    case "number":
      return GraphQLFloat;
    case "boolean":
      return GraphQLBoolean;
    case "json":
      return GraphQLString;
    default:
      return null;
  }
}

/** Module-level logger, configurable via setGraphQLLogger */
let moduleLogger: Logger = consoleLogger;

/** Set the logger used by schema-to-graphql utilities */
export function setGraphQLLogger(logger: Logger): void {
  moduleLogger = logger;
}

/** Regex for valid GraphQL names */
const GRAPHQL_NAME_RE = /^[_A-Za-z][_0-9A-Za-z]*$/;

/**
 * Convert a schema name to PascalCase for GraphQL type naming.
 * Strips illegal characters and validates the result.
 * e.g. "order_item" → "OrderItem"
 */
function toPascalCase(name: string): string {
  const raw = name
    .split(/[_-]/)
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join("");

  // Strip characters not allowed in GraphQL names
  const sanitized = raw.replace(/[^_0-9A-Za-z]/g, "");

  // Ensure name starts with a letter or underscore
  const result = GRAPHQL_NAME_RE.test(sanitized) ? sanitized : `_${sanitized}`;

  if (result !== raw) {
    moduleLogger.warn(
      `[schema-to-graphql] Name "${name}" sanitized to "${result}" for GraphQL compatibility`,
    );
  }

  return result;
}

// ── Link-based relation field generation ──────────────────────────────────

/** Context for resolving link relation fields */
export interface LinkResolverContext {
  /** Data provider for fetching related records (optional — resolvers degrade gracefully) */
  dataProvider?: DataProvider;
  /** Tenant ID for data isolation */
  tenantId?: string;
  /** Authenticated actor for permission-based data masking */
  actor?: Actor;
  /** Permission groups for data masking unmask checks */
  permissionGroups?: PermissionGroupDefinition[];
  /** Schema definitions map for data masking lookups */
  schemaMap?: Map<string, SchemaDefinition>;
}

/** Field types whose masked values cannot be represented as strings in GraphQL (must become null) */
const NON_STRING_FIELD_TYPES = new Set(["number", "boolean", "date", "datetime", "json"]);

/**
 * Apply data masking to a single record using context actor and permissions.
 * Returns the masked record with non-string masked fields coerced to null.
 */
function applyLinkMasking(
  record: Record<string, unknown>,
  schemaName: string,
  ctx: LinkResolverContext,
): Record<string, unknown> {
  if (!ctx.actor || !ctx.schemaMap) return record;
  const schemaDef = ctx.schemaMap.get(schemaName);
  if (!schemaDef) return record;
  const maskOpts: MaskRecordOptions = {
    actor: ctx.actor,
    groups: ctx.permissionGroups ?? [],
    capabilityName: schemaDef.name,
  };
  const masked = maskRecord(record, schemaDef, maskOpts);
  // Coerce masked non-string fields to null (GraphQL type mismatch)
  for (const [fieldName, fieldDef] of Object.entries(schemaDef.fields)) {
    if (
      NON_STRING_FIELD_TYPES.has(fieldDef.type) &&
      typeof masked[fieldName] === "string" &&
      masked[fieldName] !== record[fieldName]
    ) {
      masked[fieldName] = null;
    }
  }
  return masked;
}

/**
 * Apply data masking to an array of records.
 */
function applyLinkMaskingArray(
  records: Record<string, unknown>[],
  schemaName: string,
  ctx: LinkResolverContext,
): Record<string, unknown>[] {
  return records.map((r) => applyLinkMasking(r, schemaName, ctx));
}

/**
 * Compute link-based relation fields for a given schema.
 *
 * Returns a thunk (for lazy evaluation) that produces the relation fields.
 * This avoids circular reference issues since GraphQL types reference each other.
 *
 * FK naming convention (matches schema-to-drizzle.ts):
 * - many_to_one / one_to_one: `{to}_id` column on `from` table
 * - one_to_many: `{from}_id` column on `to` table
 * - many_to_many: junction table `_link_{name}` with `{from}_id` and `{to}_id`
 */
function buildLinkFields(
  schemaName: string,
  links: LinkDefinition[],
  typeMap: Map<string, GraphQLObjectType>,
): Record<
  string,
  {
    type: GraphQLOutputType;
    description?: string;
    resolve: (
      obj: Record<string, unknown>,
      args: Record<string, unknown>,
      ctx: LinkResolverContext,
    ) => Promise<unknown>;
  }
> {
  const fields: Record<
    string,
    {
      type: GraphQLOutputType;
      description?: string;
      resolve: (
        obj: Record<string, unknown>,
        args: Record<string, unknown>,
        ctx: LinkResolverContext,
      ) => Promise<unknown>;
    }
  > = {};

  for (const link of links) {
    const isFrom = link.from === schemaName;
    const isTo = link.to === schemaName;
    if (!isFrom && !isTo) continue;

    switch (link.cardinality) {
      case "many_to_one": {
        if (isFrom) {
          // From side: singular field pointing to the "to" schema
          // FK column: `{to}_id` on from table
          const relatedType = typeMap.get(link.to);
          if (!relatedType) break;
          const fkColumn = `${link.to}_id`;
          const fieldName = link.to;
          const label = link.label?.from;
          fields[fieldName] = {
            type: relatedType,
            description: label ?? `Related ${link.to}`,
            resolve: async (obj, _args, ctx) => {
              const fkValue = obj[fkColumn] as string | undefined;
              if (!fkValue || !ctx.dataProvider) return null;
              try {
                const record = await ctx.dataProvider.get(link.to, fkValue, {
                  tenantId: ctx.tenantId,
                });
                return record
                  ? applyLinkMasking(record as Record<string, unknown>, link.to, ctx)
                  : null;
              } catch (err) {
                moduleLogger.error(
                  `[link-resolver] Failed to resolve ${link.name} (many_to_one from): ${err}`,
                );
                return null;
              }
            },
          };
        }
        if (isTo) {
          // To side (reverse): plural field listing records from "from" schema
          // FK column: `{to}_id` on from table → filter from table where {to}_id = this.id
          const relatedType = typeMap.get(link.from);
          if (!relatedType) break;
          const fkColumn = `${link.to}_id`;
          const fieldName = `${link.from}s`;
          const label = link.label?.to;
          fields[fieldName] = {
            type: new GraphQLNonNull(new GraphQLList(new GraphQLNonNull(relatedType))),
            description: label ?? `Related ${link.from} records`,
            resolve: async (obj, _args, ctx) => {
              const id = obj.id as string;
              if (!id || !ctx.dataProvider) return [];
              try {
                const records = await ctx.dataProvider.query(
                  link.from,
                  { [fkColumn]: id },
                  { tenantId: ctx.tenantId },
                );
                return applyLinkMaskingArray(
                  records as Record<string, unknown>[],
                  link.from,
                  ctx,
                );
              } catch (err) {
                moduleLogger.error(
                  `[link-resolver] Failed to resolve ${link.name} (many_to_one to): ${err}`,
                );
                return [];
              }
            },
          };
        }
        break;
      }

      case "one_to_many": {
        if (isFrom) {
          // From side: plural field listing records from "to" schema
          // FK column: `{from}_id` on to table
          const relatedType = typeMap.get(link.to);
          if (!relatedType) break;
          const fkColumn = `${link.from}_id`;
          const fieldName = `${link.to}s`;
          const label = link.label?.from;
          fields[fieldName] = {
            type: new GraphQLNonNull(new GraphQLList(new GraphQLNonNull(relatedType))),
            description: label ?? `Related ${link.to} records`,
            resolve: async (obj, _args, ctx) => {
              const id = obj.id as string;
              if (!id || !ctx.dataProvider) return [];
              try {
                const records = await ctx.dataProvider.query(
                  link.to,
                  { [fkColumn]: id },
                  { tenantId: ctx.tenantId },
                );
                return applyLinkMaskingArray(
                  records as Record<string, unknown>[],
                  link.to,
                  ctx,
                );
              } catch (err) {
                moduleLogger.error(
                  `[link-resolver] Failed to resolve ${link.name} (one_to_many from): ${err}`,
                );
                return [];
              }
            },
          };
        }
        if (isTo) {
          // To side (reverse): singular field pointing to "from" schema
          // FK column: `{from}_id` on to table
          const relatedType = typeMap.get(link.from);
          if (!relatedType) break;
          const fkColumn = `${link.from}_id`;
          const fieldName = link.from;
          const label = link.label?.to;
          fields[fieldName] = {
            type: relatedType,
            description: label ?? `Related ${link.from}`,
            resolve: async (obj, _args, ctx) => {
              const fkValue = obj[fkColumn] as string | undefined;
              if (!fkValue || !ctx.dataProvider) return null;
              try {
                const record = await ctx.dataProvider.get(link.from, fkValue, {
                  tenantId: ctx.tenantId,
                });
                return record
                  ? applyLinkMasking(record as Record<string, unknown>, link.from, ctx)
                  : null;
              } catch (err) {
                moduleLogger.error(
                  `[link-resolver] Failed to resolve ${link.name} (one_to_many to): ${err}`,
                );
                return null;
              }
            },
          };
        }
        break;
      }

      case "one_to_one": {
        if (isFrom) {
          // FK column: `{to}_id` on from table (same as many_to_one from side)
          const relatedType = typeMap.get(link.to);
          if (!relatedType) break;
          const fkColumn = `${link.to}_id`;
          const fieldName = link.to;
          const label = link.label?.from;
          fields[fieldName] = {
            type: relatedType,
            description: label ?? `Related ${link.to}`,
            resolve: async (obj, _args, ctx) => {
              const fkValue = obj[fkColumn] as string | undefined;
              if (!fkValue || !ctx.dataProvider) return null;
              try {
                const record = await ctx.dataProvider.get(link.to, fkValue, {
                  tenantId: ctx.tenantId,
                });
                return record
                  ? applyLinkMasking(record as Record<string, unknown>, link.to, ctx)
                  : null;
              } catch (err) {
                moduleLogger.error(
                  `[link-resolver] Failed to resolve ${link.name} (one_to_one from): ${err}`,
                );
                return null;
              }
            },
          };
        }
        if (isTo) {
          // Reverse: query from table for record where {to}_id = this.id
          const relatedType = typeMap.get(link.from);
          if (!relatedType) break;
          const fkColumn = `${link.to}_id`;
          const fieldName = link.from;
          const label = link.label?.to;
          fields[fieldName] = {
            type: relatedType,
            description: label ?? `Related ${link.from}`,
            resolve: async (obj, _args, ctx) => {
              const id = obj.id as string;
              if (!id || !ctx.dataProvider) return null;
              try {
                const results = await ctx.dataProvider.query(
                  link.from,
                  { [fkColumn]: id },
                  { tenantId: ctx.tenantId },
                );
                const first = results[0] ?? null;
                return first
                  ? applyLinkMasking(first as Record<string, unknown>, link.from, ctx)
                  : null;
              } catch (err) {
                moduleLogger.error(
                  `[link-resolver] Failed to resolve ${link.name} (one_to_one to): ${err}`,
                );
                return null;
              }
            },
          };
        }
        break;
      }

      case "many_to_many": {
        // Both sides get a plural field. Resolve via junction table `_link_{name}`.
        const otherSchema = isFrom ? link.to : link.from;
        const relatedType = typeMap.get(otherSchema);
        if (!relatedType) break;

        const fieldName = `${otherSchema}s`;
        const label = isFrom ? link.label?.from : link.label?.to;
        const junctionTable = `_link_${link.name}`;
        const thisFkCol = isFrom ? `${link.from}_id` : `${link.to}_id`;
        const otherFkCol = isFrom ? `${link.to}_id` : `${link.from}_id`;

        fields[fieldName] = {
          type: new GraphQLNonNull(new GraphQLList(new GraphQLNonNull(relatedType))),
          description: label ?? `Related ${otherSchema} records`,
          resolve: async (obj, _args, ctx) => {
            const id = obj.id as string;
            const dp = ctx.dataProvider;
            if (!id || !dp) return [];
            try {
              // Query junction table for matching rows
              const junctionRows = await dp.query(
                junctionTable,
                { [thisFkCol]: id },
                { tenantId: ctx.tenantId },
              );
              // Fetch each related record by ID
              const relatedIds = junctionRows
                .map((row) => row[otherFkCol] as string)
                .filter(Boolean);
              if (relatedIds.length === 0) return [];
              const results = await Promise.all(
                relatedIds.map(async (relatedId) => {
                  try {
                    return await dp.get(otherSchema, relatedId, {
                      tenantId: ctx.tenantId,
                    });
                  } catch (err) {
                    moduleLogger.error(
                      `[link-resolver] Failed to fetch ${otherSchema}#${relatedId} in ${link.name}: ${err}`,
                    );
                    return null;
                  }
                }),
              );
              const filtered = results.filter(Boolean) as Record<string, unknown>[];
              return applyLinkMaskingArray(filtered, otherSchema, ctx);
            } catch (err) {
              moduleLogger.error(
                `[link-resolver] Failed to resolve ${link.name} (many_to_many): ${err}`,
              );
              return [];
            }
          },
        };
        break;
      }
    }
  }

  return fields;
}

/**
 * Generate a GraphQL object type from a LinchKit SchemaDefinition.
 * Includes system fields (id, tenant_id, created_at, etc.) and user-defined fields.
 * When stateMachines is provided, state fields generate proper GraphQLEnumType.
 * When links and typeMap are provided, adds link-based relation resolver fields.
 */
export function generateGraphQLObjectType(
  schema: SchemaDefinition,
  stateMachines?: Map<string, StateDefinition>,
  links?: LinkDefinition[],
  typeMap?: Map<string, GraphQLObjectType>,
): GraphQLObjectType {
  const typeName = toPascalCase(schema.name);

  return new GraphQLObjectType({
    name: typeName,
    description: schema.description ?? schema.label,
    fields: () => {
      const fields: Record<
        string,
        {
          type: GraphQLOutputType;
          description?: string;
          resolve?: (
            obj: Record<string, unknown>,
            args: Record<string, unknown>,
            ctx: LinkResolverContext,
          ) => unknown;
        }
      > = {};

      // System fields — use safe resolvers to handle missing values
      fields.id = {
        type: new GraphQLNonNull(GraphQLID),
        resolve: (obj: Record<string, unknown>) => obj.id ?? "",
      };
      fields.tenant_id = {
        type: GraphQLString,
        resolve: (obj: Record<string, unknown>) => obj.tenant_id ?? null,
      };
      fields.created_at = {
        type: new GraphQLNonNull(GraphQLString),
        description: "ISO 8601 timestamp",
        resolve: (obj: Record<string, unknown>) => obj.created_at ?? new Date().toISOString(),
      };
      fields.updated_at = {
        type: new GraphQLNonNull(GraphQLString),
        description: "ISO 8601 timestamp",
        resolve: (obj: Record<string, unknown>) => obj.updated_at ?? new Date().toISOString(),
      };
      fields.created_by = {
        type: GraphQLString,
        resolve: (obj: Record<string, unknown>) => obj.created_by ?? null,
      };
      fields.updated_by = {
        type: GraphQLString,
        resolve: (obj: Record<string, unknown>) => obj.updated_by ?? null,
      };
      fields._version = {
        type: new GraphQLNonNull(GraphQLInt),
        resolve: (obj: Record<string, unknown>) => obj._version ?? 1,
      };

      // User-defined fields — always nullable in output with safe resolvers
      // to prevent crashes when records are missing fields
      const defaultLocale = schema.i18n?.defaultLocale;

      for (const [fieldName, field] of Object.entries(schema.fields)) {
        const graphqlType = mapFieldToGraphQLType(field, fieldName, schema, stateMachines);
        if (!graphqlType) {
          continue;
        }

        const name = fieldName;

        if (field.translatable) {
          // Translatable fields: resolve JSONB locale map → string.
          // If the DataProvider already resolved (locale was provided), value is a string.
          // If not resolved, value is a JSONB locale map — resolve using context locale or default.
          fields[fieldName] = {
            type: graphqlType,
            description: field.description ?? field.label,
            resolve: (
              obj: Record<string, unknown>,
              _args: Record<string, unknown>,
              ctx: LinkResolverContext & { locale?: string },
            ) => {
              const raw = obj[name];
              if (raw === null || raw === undefined) return null;
              if (typeof raw === "string") return raw;
              // Still a JSONB object — resolve with context locale
              return resolveTranslatableValue(raw, ctx?.locale, defaultLocale) ?? null;
            },
          };

          // Also generate a `{field}_i18n` field that returns the full JSONB locale map as JSON string
          fields[`${fieldName}_i18n`] = {
            type: GraphQLString,
            description: `All translations for ${field.label ?? fieldName} (JSON-encoded locale map)`,
            resolve: (obj: Record<string, unknown>) => {
              const raw = obj[name];
              if (raw === null || raw === undefined) return null;
              if (typeof raw === "string") return null; // Already resolved, no full map available
              return JSON.stringify(raw);
            },
          };
        } else {
          fields[fieldName] = {
            type: graphqlType, // Always nullable in output to prevent resolver crashes
            description: field.description ?? field.label,
            resolve: (obj: Record<string, unknown>) => obj[name] ?? null,
          };
        }
      }

      // Link-based relation fields
      if (links && typeMap) {
        const linkFields = buildLinkFields(schema.name, links, typeMap);
        for (const [name, fieldConfig] of Object.entries(linkFields)) {
          // Avoid overwriting existing fields (e.g., if a schema has a field named same as relation)
          if (!fields[name]) {
            fields[name] = fieldConfig;
          }
        }
      }

      return fields;
    },
  });
}

/**
 * Generate a GraphQL input type from a LinchKit SchemaDefinition.
 * Excludes system fields — those are managed by the server.
 * When stateMachines is provided, state fields generate proper GraphQLEnumType.
 */
export function generateGraphQLInputType(
  schema: SchemaDefinition,
  stateMachines?: Map<string, StateDefinition>,
): GraphQLInputObjectType {
  const typeName = `${toPascalCase(schema.name)}Input`;

  return new GraphQLInputObjectType({
    name: typeName,
    description: `Input type for creating/updating ${schema.label ?? schema.name}`,
    fields: () => {
      const fields: Record<string, GraphQLInputFieldConfig> = {};

      for (const [fieldName, field] of Object.entries(schema.fields)) {
        // Derived fields are read-only — exclude from input types (spec 48)
        if (field.derived) {
          continue;
        }

        const graphqlType = mapFieldToGraphQLInputType(field, fieldName, schema, stateMachines);
        if (!graphqlType) {
          continue;
        }

        fields[fieldName] = {
          type: field.required ? new GraphQLNonNull(graphqlType) : graphqlType,
          description: field.description ?? field.label,
        };
      }

      return fields;
    },
  });
}

/**
 * Clear the enum type cache. Useful for testing to avoid cross-test contamination.
 */
export function clearEnumTypeCache(): void {
  enumTypeCache.clear();
}

/**
 * Generate a GraphQL input type from an ActionDefinition's input fields.
 * Returns null if the action has no input definition.
 */
export function generateActionInputType(action: ActionDefinition): GraphQLInputObjectType | null {
  if (!action.input || Object.keys(action.input).length === 0) {
    return null;
  }

  const typeName = `${toPascalCase(action.name)}Input`;

  return new GraphQLInputObjectType({
    name: typeName,
    description: `Input type for ${action.label ?? action.name}`,
    fields: () => {
      const fields: Record<string, GraphQLInputFieldConfig> = {};

      const inputFields = action.input ?? {};
      for (const [fieldName, field] of Object.entries(inputFields)) {
        const graphqlType = mapFieldToGraphQLInputType(field);
        if (!graphqlType) {
          continue;
        }

        fields[fieldName] = {
          type: field.required ? new GraphQLNonNull(graphqlType) : graphqlType,
          description: field.description ?? field.label,
        };
      }

      return fields;
    },
  });
}
