/**
 * @linchkit/devtools — Testing tools + development debugging + documentation + methodology + governance
 *
 * testRule / testStateMachine / validateCapability / getAvailableTransitions
 * + documentation generators, methodology checks, governance tools
 */

export const VERSION = "0.0.1";

// === Source patcher (#566): injected TS-AST patcher for core's SourcePatcher seam ===
export type { SourcePatcher, SourcePatchRequest, SourcePatchResult } from "@linchkit/core";
// === AI Evaluation Framework (spec 69) ===
export {
  type AnomalyEvalOutput,
  type AnomalyEvalOutputItem,
  type AnomalyFixtureContext,
  type AnomalyFixtureInput,
  type AnomalyUsageEventInput,
  anomalyMatchers,
  type BaselineDiff,
  type BaselineFile,
  type BaselineFixtureEntry,
  type BaselineLayoutOptions,
  type CliDeps,
  type CliRunResult,
  canonicalPath,
  compareToBaseline,
  createMatcherRegistry,
  createScenarioRegistry,
  DEFAULT_BASELINES_DIR,
  datedArchivePath,
  type EvalFixture,
  estimateCost,
  findBaselineEntry,
  hashFixture,
  type InlineCatalogAction,
  type IntentEvalOutput,
  type IntentFixtureContext,
  type IntentFixtureInput,
  intentMatchers,
  type LoadBaselineOptions,
  loadCanonicalBaseline,
  loadFixtures,
  type MarkdownReportOptions,
  type MatcherFn,
  type MatcherInvocation,
  type MatcherRegistry,
  type MatcherResult,
  type OntologyRegistryLike,
  type PatternEvalOutput,
  type PatternEvalOutputItem,
  type PatternExecLogInput,
  type PatternFixtureContext,
  type PatternFixtureInput,
  patternMatchers,
  RegressionError,
  RUNNER_VERSION,
  type RunDeps,
  type RunOptions,
  type RunReport,
  registerAnomalyMatchers,
  registerIntentMatchers,
  registerPatternMatchers,
  registerWatcherMatchers,
  renderJsonReport,
  renderMarkdownReport,
  reportToBaselineFile,
  runCli,
  runEval,
  type ScenarioAdapter,
  type ScenarioRegistry,
  type WatcherDefInput,
  type WatcherEvalOutput,
  type WatcherEvalOutputItem,
  type WatcherFixtureContext,
  type WatcherFixtureInput,
  type WatcherScheduleTriggerInput,
  type WatcherSetChangeTriggerInput,
  type WatcherStalenessTriggerInput,
  type WatcherThresholdTriggerInput,
  type WatcherTriggerInput,
  type WriteBaselineOptions,
  watcherMatchers,
  writeCanonicalBaseline,
} from "./ai-eval";
// === Documentation: API doc generation, Markdown, OpenAPI, Capability Spec, Search ===
export {
  type ActionDoc,
  type ApiDocGeneratorOptions,
  actionToDoc,
  type CapabilityActionDoc,
  type CapabilityEntityDoc,
  type CapabilityRelationDoc,
  type CapabilityRuleDoc,
  type CapabilitySpecDoc,
  type CapabilityStateMachineDoc,
  type CapabilityViewDoc,
  createDocSearchIndex,
  DocSearchIndex,
  type DocSearchOptions,
  type DocSearchResult,
  type EntityDoc,
  entityToDoc,
  type FieldDoc,
  fieldToDoc,
  generateApiDoc,
  generateCapabilityDoc,
  generateOpenAPISpec,
  type MarkdownRenderOptions,
  type OpenAPIGeneratorOptions,
  type OpenAPIOperation,
  type OpenAPIPathItem,
  type OpenAPISchemaObject,
  type OpenAPISpec,
  renderActionDoc,
  renderCapabilityDoc,
  renderEntityDoc,
  renderSystemDoc,
  type SystemDoc,
} from "./documentation";
// === Governance: documentation validation, spec tracking, changelog ===
export {
  type ChangelogOptions,
  type ConventionalCommit,
  type DocCompleteness,
  type DocIssue,
  generateChangelog,
  generateSpecReport,
  generateVersionedChangelog,
  parseConventionalCommit,
  type SpecProgressReport,
  type SpecStatus,
  type SpecStatusValue,
  SpecTracker,
  type VersionGroup,
  validateActionDoc,
  validateCapabilityDoc as validateCapabilityDocCompleteness,
  validateEntityDoc,
  /** @deprecated Use validateEntityDoc instead */
  validateSchemaDoc,
} from "./governance";
// === Methodology: code quality, project structure, convention checking ===
export {
  type ActionInfo,
  type CapabilityLintIssue,
  type CapabilityLintResult,
  type CommitInfo,
  checkActionDefinitions,
  checkCommitMessages,
  checkEntityDefinitions,
  checkFileNaming,
  checkImportPatterns,
  type DirectoryEntry,
  type EntityInfo,
  type ExportBoundaryConfig,
  type FileContent,
  lintCapability,
  type QualityIssue,
  type QualityReport,
  type Severity,
  type StructureExpectation,
  validateCapabilityStructure,
  validateExportPatterns,
  validateNamingConventions,
  validateProjectStructure,
} from "./methodology";
export { patchNamedConstant } from "./patch-named-constant";
export type { TestRuleInput } from "./test-rule";
export { testRule } from "./test-rule";
export type {
  MockAIResponse,
  MockAIService,
  TestRuntime,
  TestRuntimeOptions,
} from "./test-runtime";
export { createTestActor, createTestRuntime, mockAIService } from "./test-runtime";
export type { TestTransitionInput } from "./test-state";
export { getAvailableTransitions, testStateMachine } from "./test-state";
export type { CapabilityValidationResult, ValidationIssue } from "./validate-capability";
export { validateCapability } from "./validate-capability";
