import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import type { CapabilityDefinition } from "@linchkit/core";

const GENERATED_HEADER = `@import "@linchkit/ui-kit/styles.css";

/*
 * Generated by linch dev from capability.ui.styles declarations.
 *
 * Load order is semantic:
 * 1. ui-kit base styles
 * 2. capability styles in config.capabilities order
 *
 * Later imports override earlier imports. Conflicts are not resolved by the framework.
 */
`;

function renderCapabilityStyles(capabilities: CapabilityDefinition[]): string {
  const imports = new Set<string>();

  for (const capability of capabilities) {
    for (const styleEntry of capability.ui?.styles ?? []) {
      if (styleEntry) {
        imports.add(styleEntry);
      }
    }
  }

  const lines = Array.from(imports).map((styleEntry) => `@import "${styleEntry}";`);
  return `${GENERATED_HEADER}${lines.length > 0 ? `\n${lines.join("\n")}\n` : "\n"}`;
}

export function generateCapabilityStylesheet(
  capabilities: CapabilityDefinition[],
  cwd?: string,
): { path: string; updated: boolean } | null {
  const baseDir = cwd ?? process.cwd();
  const stylesheetPath = resolve(
    baseDir,
    "addons/adapter-ui-react/cap-adapter-ui-react/src/capability-styles.css",
  );

  if (!existsSync(resolve(baseDir, "addons/adapter-ui-react/cap-adapter-ui-react/package.json"))) {
    return null;
  }

  const nextContent = renderCapabilityStyles(capabilities);
  const prevContent = existsSync(stylesheetPath) ? readFileSync(stylesheetPath, "utf8") : "";

  if (prevContent === nextContent) {
    return { path: stylesheetPath, updated: false };
  }

  mkdirSync(dirname(stylesheetPath), { recursive: true });
  writeFileSync(stylesheetPath, nextContent);

  return { path: stylesheetPath, updated: true };
}
