/**
 * Schema-to-GraphQL generator
 *
 * Converts a LinchKit EntityDefinition into GraphQL object and input types
 * for use in a GraphQL API layer. Supports link-based relation resolvers.
 */

import type {
  ActionDefinition,
  FieldDefinition,
  RelationDefinition,
  Logger,
  EntityDefinition,
  StateDefinition,
} from "@linchkit/core";
import { I18N_RAW_KEY, resolveTranslatableValue } from "@linchkit/core";
import { consoleLogger } from "@linchkit/core/server";

export type { RelationResolverContext } from "./relation-resolvers";

import {
  GraphQLBoolean,
  GraphQLEnumType,
  GraphQLFloat,
  GraphQLID,
  type GraphQLInputFieldConfig,
  GraphQLInputObjectType,
  type GraphQLInputType,
  GraphQLInt,
  GraphQLNonNull,
  GraphQLObjectType,
  type GraphQLOutputType,
  GraphQLString,
} from "graphql";
import type { RelationResolverContext } from "./relation-resolvers";
import { buildRelationFields } from "./relation-resolvers";

// Cache for reusing GraphQLEnumType instances across output and input types
const enumTypeCache = new Map<string, GraphQLEnumType>();

/**
 * Sanitize a value string into a valid GraphQL enum value name.
 * GraphQL enum values must match /^[_A-Za-z][_0-9A-Za-z]*$/.
 */
function sanitizeEnumValue(value: string): string {
  // Replace non-alphanumeric/underscore characters with underscores
  let sanitized = value.replace(/[^_0-9A-Za-z]/g, "_");
  // Ensure it starts with a letter or underscore
  if (!/^[_A-Za-z]/.test(sanitized)) {
    sanitized = `_${sanitized}`;
  }
  return sanitized;
}

/**
 * Build or retrieve a cached GraphQLEnumType for an enum field with options.
 */
function getEnumTypeForField(
  schema: EntityDefinition,
  fieldName: string,
  options: Array<{ value: string; label?: string }>,
): GraphQLEnumType {
  const enumName = `${toPascalCase(schema.name)}${toPascalCase(fieldName)}Enum`;
  const cached = enumTypeCache.get(enumName);
  if (cached) return cached;

  const enumType = new GraphQLEnumType({
    name: enumName,
    values: Object.fromEntries(
      options.map((o) => [sanitizeEnumValue(o.value), { value: o.value, description: o.label }]),
    ),
  });
  enumTypeCache.set(enumName, enumType);
  return enumType;
}

/**
 * Build or retrieve a cached GraphQLEnumType for a state field from a StateDefinition.
 */
function getEnumTypeForState(
  schema: EntityDefinition,
  fieldName: string,
  stateDef: StateDefinition,
): GraphQLEnumType {
  const enumName = `${toPascalCase(schema.name)}${toPascalCase(fieldName)}State`;
  const cached = enumTypeCache.get(enumName);
  if (cached) return cached;

  const meta = stateDef.meta ?? {};
  const enumType = new GraphQLEnumType({
    name: enumName,
    values: Object.fromEntries(
      stateDef.states.map((s) => [
        sanitizeEnumValue(s),
        { value: s, description: (meta as Record<string, { label?: string }>)[s]?.label },
      ]),
    ),
  });
  enumTypeCache.set(enumName, enumType);
  return enumType;
}

/** Map of state machine name → StateDefinition, used to resolve state fields */
type StateMachineMap = Map<string, StateDefinition>;

/**
 * Map a LinchKit field type to a GraphQL output type.
 * Generates GraphQLEnumType for enum fields with options and state fields with known machines.
 */
function mapFieldToGraphQLType(
  field: FieldDefinition,
  fieldName: string,
  schema: EntityDefinition,
  stateMachines?: StateMachineMap,
): GraphQLOutputType | null {
  switch (field.type) {
    case "string":
    case "text":
    case "date":
    case "datetime":
      return GraphQLString;
    case "enum": {
      if (field.options?.length) {
        return getEnumTypeForField(schema, fieldName, field.options);
      }
      return GraphQLString;
    }
    case "state": {
      const machineKey = field.machine;
      const machine = machineKey ? stateMachines?.get(machineKey) : undefined;
      if (machine?.states?.length) {
        return getEnumTypeForState(schema, fieldName, machine);
      }
      return GraphQLString;
    }
    case "number":
      return GraphQLFloat;
    case "boolean":
      return GraphQLBoolean;
    case "json":
      // JSON fields are represented as String (serialized JSON)
      return GraphQLString;
    default:
      return null;
  }
}

/**
 * Map a LinchKit field type to a GraphQL input type.
 * Reuses the same cached enum types generated by mapFieldToGraphQLType.
 *
 * For translatable fields, the input type is always GraphQLString.
 * Clients pass either a plain string (single-locale shortcut) or a JSON-encoded
 * locale map (e.g., '{"en":"Hello","zh-CN":"你好"}').
 */
export function mapFieldToGraphQLInputType(
  field: FieldDefinition,
  fieldName?: string,
  schema?: EntityDefinition,
  stateMachines?: StateMachineMap,
): GraphQLInputType | null {
  // Translatable fields accept String input (plain string or JSON-encoded locale map)
  if (field.translatable) {
    return GraphQLString;
  }

  switch (field.type) {
    case "string":
    case "text":
    case "date":
    case "datetime":
      return GraphQLString;
    case "enum": {
      if (schema && fieldName && field.options?.length) {
        return getEnumTypeForField(schema, fieldName, field.options);
      }
      return GraphQLString;
    }
    case "state": {
      if (schema && fieldName) {
        const machineKey = field.machine;
        const machine = machineKey ? stateMachines?.get(machineKey) : undefined;
        if (machine?.states?.length) {
          return getEnumTypeForState(schema, fieldName, machine);
        }
      }
      return GraphQLString;
    }
    case "number":
      return GraphQLFloat;
    case "boolean":
      return GraphQLBoolean;
    case "json":
      return GraphQLString;
    default:
      return null;
  }
}

/** Module-level logger, configurable via setGraphQLLogger */
let moduleLogger: Logger = consoleLogger;

/** Set the logger used by schema-to-graphql utilities */
export function setGraphQLLogger(logger: Logger): void {
  moduleLogger = logger;
}

/** Regex for valid GraphQL names */
const GRAPHQL_NAME_RE = /^[_A-Za-z][_0-9A-Za-z]*$/;

/**
 * Convert a schema name to PascalCase for GraphQL type naming.
 * Strips illegal characters and validates the result.
 * e.g. "order_item" → "OrderItem"
 */
function toPascalCase(name: string): string {
  const raw = name
    .split(/[_-]/)
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join("");

  // Strip characters not allowed in GraphQL names
  const sanitized = raw.replace(/[^_0-9A-Za-z]/g, "");

  // Ensure name starts with a letter or underscore
  const result = GRAPHQL_NAME_RE.test(sanitized) ? sanitized : `_${sanitized}`;

  if (result !== raw) {
    moduleLogger.warn(
      `[schema-to-graphql] Name "${name}" sanitized to "${result}" for GraphQL compatibility`,
    );
  }

  return result;
}

/**
 * Generate a GraphQL object type from a LinchKit EntityDefinition.
 * Includes system fields (id, tenant_id, created_at, etc.) and user-defined fields.
 * When stateMachines is provided, state fields generate proper GraphQLEnumType.
 * When links and typeMap are provided, adds link-based relation resolver fields.
 */
export function generateGraphQLObjectType(
  schema: EntityDefinition,
  stateMachines?: Map<string, StateDefinition>,
  links?: RelationDefinition[],
  typeMap?: Map<string, GraphQLObjectType>,
): GraphQLObjectType {
  const typeName = toPascalCase(schema.name);

  return new GraphQLObjectType({
    name: typeName,
    description: schema.description ?? schema.label,
    fields: () => {
      const fields: Record<
        string,
        {
          type: GraphQLOutputType;
          description?: string;
          resolve?: (
            obj: Record<string, unknown>,
            args: Record<string, unknown>,
            ctx: RelationResolverContext,
          ) => unknown;
        }
      > = {};

      // System fields — use safe resolvers to handle missing values
      fields.id = {
        type: new GraphQLNonNull(GraphQLID),
        resolve: (obj: Record<string, unknown>) => obj.id ?? "",
      };
      fields.tenant_id = {
        type: GraphQLString,
        resolve: (obj: Record<string, unknown>) => obj.tenant_id ?? null,
      };
      fields.created_at = {
        type: new GraphQLNonNull(GraphQLString),
        description: "ISO 8601 timestamp",
        resolve: (obj: Record<string, unknown>) => {
          const v = obj.created_at;
          if (v instanceof Date) return v.toISOString();
          return v ?? new Date().toISOString();
        },
      };
      fields.updated_at = {
        type: new GraphQLNonNull(GraphQLString),
        description: "ISO 8601 timestamp",
        resolve: (obj: Record<string, unknown>) => {
          const v = obj.updated_at;
          if (v instanceof Date) return v.toISOString();
          return v ?? new Date().toISOString();
        },
      };
      fields.created_by = {
        type: GraphQLString,
        resolve: (obj: Record<string, unknown>) => obj.created_by ?? null,
      };
      fields.updated_by = {
        type: GraphQLString,
        resolve: (obj: Record<string, unknown>) => obj.updated_by ?? null,
      };
      fields._version = {
        type: new GraphQLNonNull(GraphQLInt),
        resolve: (obj: Record<string, unknown>) => obj._version ?? 1,
      };

      // User-defined fields — always nullable in output with safe resolvers
      // to prevent crashes when records are missing fields
      const defaultLocale = schema.i18n?.defaultLocale;

      for (const [fieldName, field] of Object.entries(schema.fields)) {
        const graphqlType = mapFieldToGraphQLType(field, fieldName, schema, stateMachines);
        if (!graphqlType) {
          continue;
        }

        const name = fieldName;

        if (field.translatable) {
          // Translatable fields: resolve JSONB locale map → string.
          // If the DataProvider already resolved (locale was provided), value is a string.
          // If not resolved, value is a JSONB locale map — resolve using context locale or default.
          fields[fieldName] = {
            type: graphqlType,
            description: field.description ?? field.label,
            resolve: (
              obj: Record<string, unknown>,
              _args: Record<string, unknown>,
              ctx: RelationResolverContext & { locale?: string },
            ) => {
              const raw = obj[name];
              if (raw === null || raw === undefined) return null;
              if (typeof raw === "string") return raw;
              // Still a JSONB object — resolve with context locale
              return resolveTranslatableValue(raw, ctx?.locale, defaultLocale) ?? null;
            },
          };

          // Also generate a `{field}_i18n` field that returns the full JSONB locale map as JSON string.
          // After resolveTranslatableRow, the raw JSONB is stashed under I18N_RAW_KEY.
          // Skip if the schema already defines a field with this name to avoid collision.
          const i18nFieldName = `${fieldName}_i18n`;
          if (i18nFieldName in schema.fields) {
            moduleLogger.warn(
              `[schema-to-graphql] Entity "${schema.name}" already has field "${i18nFieldName}" — skipping auto-generated i18n field for "${fieldName}"`,
            );
          } else {
            fields[i18nFieldName] = {
              type: GraphQLString,
              description: `All translations for ${field.label ?? fieldName} (JSON-encoded locale map)`,
              resolve: (obj: Record<string, unknown>) => {
                // First check the stashed raw locale map (set by resolveTranslatableRow)
                const rawMap = obj[I18N_RAW_KEY] as Record<string, unknown> | undefined;
                if (rawMap && rawMap[name] !== undefined && rawMap[name] !== null) {
                  return JSON.stringify(rawMap[name]);
                }
                // Fallback: value might still be a JSONB object (not yet resolved)
                const raw = obj[name];
                if (raw === null || raw === undefined) return null;
                if (typeof raw === "string") return null;
                return JSON.stringify(raw);
              },
            };
          }
        } else if (field.type === "datetime" || field.type === "date") {
          // Date/datetime fields: ensure Date objects are serialized to ISO strings
          fields[fieldName] = {
            type: graphqlType,
            description: field.description ?? field.label,
            resolve: (obj: Record<string, unknown>) => {
              const v = obj[name];
              if (v instanceof Date) return v.toISOString();
              return v ?? null;
            },
          };
        } else {
          fields[fieldName] = {
            type: graphqlType, // Always nullable in output to prevent resolver crashes
            description: field.description ?? field.label,
            resolve: (obj: Record<string, unknown>) => obj[name] ?? null,
          };
        }
      }

      // Link-based relation fields
      if (links && typeMap) {
        const relationFields = buildRelationFields(schema.name, links, typeMap, moduleLogger);
        for (const [name, fieldConfig] of Object.entries(relationFields)) {
          // Avoid overwriting existing fields (e.g., if a schema has a field named same as relation)
          if (!fields[name]) {
            fields[name] = fieldConfig;
          }
        }
      }

      return fields;
    },
  });
}

/**
 * Generate a GraphQL input type from a LinchKit EntityDefinition.
 * Excludes system fields — those are managed by the server.
 * When stateMachines is provided, state fields generate proper GraphQLEnumType.
 * When links are provided, adds FK columns for many_to_one and one_to_one relationships
 * (e.g., department ref → department_id input field).
 */
export function generateGraphQLInputType(
  schema: EntityDefinition,
  stateMachines?: Map<string, StateDefinition>,
  links?: RelationDefinition[],
): GraphQLInputObjectType {
  const typeName = `${toPascalCase(schema.name)}Input`;

  return new GraphQLInputObjectType({
    name: typeName,
    description: `Input type for creating/updating ${schema.label ?? schema.name}`,
    fields: () => {
      const fields: Record<string, GraphQLInputFieldConfig> = {};

      for (const [fieldName, field] of Object.entries(schema.fields)) {
        // Derived fields are read-only — exclude from input types (spec 48)
        if (field.derived) {
          continue;
        }

        const graphqlType = mapFieldToGraphQLInputType(field, fieldName, schema, stateMachines);
        if (!graphqlType) {
          continue;
        }

        fields[fieldName] = {
          type: field.required ? new GraphQLNonNull(graphqlType) : graphqlType,
          description: field.description ?? field.label,
        };
      }

      // Add FK input fields for many_to_one and one_to_one links where this schema is the "from" side.
      // E.g., if purchase_request has a many_to_one link to department, add `department_id: String`.
      if (links) {
        for (const link of links) {
          if (
            link.from === schema.name &&
            (link.cardinality === "many_to_one" || link.cardinality === "one_to_one")
          ) {
            const fkFieldName = `${link.to}_id`;
            // Don't overwrite if already defined
            if (!fields[fkFieldName]) {
              fields[fkFieldName] = {
                type: GraphQLString,
                description: `FK reference to ${link.to} (from link "${link.name}")`,
              };
            }
          }
        }
      }

      return fields;
    },
  });
}

/**
 * Clear the enum type cache. Useful for testing to avoid cross-test contamination.
 */
export function clearEnumTypeCache(): void {
  enumTypeCache.clear();
}

/**
 * Generate a GraphQL input type from an ActionDefinition's input fields.
 * Returns null if the action has no input definition.
 */
export function generateActionInputType(action: ActionDefinition): GraphQLInputObjectType | null {
  if (!action.input || Object.keys(action.input).length === 0) {
    return null;
  }

  const typeName = `${toPascalCase(action.name)}Input`;

  return new GraphQLInputObjectType({
    name: typeName,
    description: `Input type for ${action.label ?? action.name}`,
    fields: () => {
      const fields: Record<string, GraphQLInputFieldConfig> = {};

      const inputFields = action.input ?? {};
      for (const [fieldName, field] of Object.entries(inputFields)) {
        const graphqlType = mapFieldToGraphQLInputType(field);
        if (!graphqlType) {
          continue;
        }

        fields[fieldName] = {
          type: field.required ? new GraphQLNonNull(graphqlType) : graphqlType,
          description: field.description ?? field.label,
        };
      }

      return fields;
    },
  });
}
