/**
 * Overlay Promotion — generates code and SQL for graduating overlay fields
 * to code-defined entity fields.
 *
 * Does NOT auto-modify source files. Outputs a PromotionPlan with:
 * - TypeScript field definition code to paste into defineEntity()
 * - SQL migration for column creation, data backfill, and _extensions cleanup
 */

import type { FieldOverlayRecord, OverlayFieldConfig } from "../types/overlay";

/** Plan for promoting an overlay field to a code-defined field */
export interface PromotionPlan {
  entityName: string;
  fieldName: string;
  overlay: FieldOverlayRecord;
  /** TypeScript code for the field definition (to paste into defineEntity) */
  fieldDefinitionCode: string;
  /** SQL for column + backfill + cleanup */
  migrationSql: string;
}

/** Allowlist pattern for SQL identifiers (table/column names) */
const SAFE_IDENTIFIER_RE = /^[a-zA-Z_][a-zA-Z0-9_]*$/;

/** Quote a SQL identifier, rejecting anything that isn't a simple name */
function quoteIdentifier(name: string): string {
  if (!SAFE_IDENTIFIER_RE.test(name)) {
    throw new Error(`Unsafe SQL identifier: ${JSON.stringify(name)}`);
  }
  return `"${name}"`;
}

/** Escape a string for use as a SQL literal (single-quoted) */
function quoteLiteral(value: string): string {
  return `'${value.replace(/'/g, "''")}'`;
}

/** Map overlay field types to PostgreSQL column types */
const SQL_TYPE_MAP: Record<string, string> = {
  string: "TEXT",
  number: "DOUBLE PRECISION",
  boolean: "BOOLEAN",
  date: "TIMESTAMPTZ",
  enum: "TEXT",
  json: "JSONB",
};

/** Map overlay field types to SQL cast expressions */
const SQL_CAST_MAP: Record<string, string> = {
  string: "TEXT",
  number: "DOUBLE PRECISION",
  boolean: "BOOLEAN",
  date: "TIMESTAMPTZ",
  enum: "TEXT",
  json: "JSONB",
};

/**
 * Generate TypeScript field definition code from an overlay record.
 *
 * Produces a single-property object entry suitable for pasting into
 * the `fields` block of a defineEntity() call.
 */
export function generateFieldCode(overlay: FieldOverlayRecord): string {
  const { fieldName, fieldType, config } = overlay;
  const props: string[] = [`type: "${fieldType}"`];

  // Add label (pick first locale or use English)
  if (config.label) {
    const firstLabel = config.label.en ?? Object.values(config.label)[0];
    if (firstLabel) {
      props.push(`label: ${JSON.stringify(firstLabel)}`);
    }
  }

  // Add description
  if (config.description) {
    props.push(`description: ${JSON.stringify(config.description)}`);
  }

  // Add constraints
  if (config.required) {
    props.push("required: true");
  }

  if (config.defaultValue !== undefined) {
    props.push(`default: ${JSON.stringify(config.defaultValue)}`);
  }

  // Numeric constraints
  if (fieldType === "number") {
    if (config.min !== undefined) {
      props.push(`min: ${config.min}`);
    }
    if (config.max !== undefined) {
      props.push(`max: ${config.max}`);
    }
  }

  // String constraints
  if (fieldType === "string" && config.maxLength !== undefined) {
    props.push(`maxLength: ${config.maxLength}`);
  }

  // Enum options
  if (fieldType === "enum" && config.enumValues?.length) {
    props.push(`options: ${JSON.stringify(config.enumValues)}`);
  }

  const key = SAFE_IDENTIFIER_RE.test(fieldName) ? fieldName : JSON.stringify(fieldName);
  return `${key}: { ${props.join(", ")} }`;
}

/**
 * Generate SQL migration for promoting an overlay field to a real column.
 *
 * Produces three statements:
 * 1. ALTER TABLE ADD COLUMN
 * 2. UPDATE to backfill from _extensions JSONB
 * 3. UPDATE to remove the key from _extensions
 */
export function generateMigrationSql(entityName: string, overlay: FieldOverlayRecord): string {
  const { fieldName, fieldType, config } = overlay;
  const sqlType = SQL_TYPE_MAP[fieldType] ?? "TEXT";
  const castType = SQL_CAST_MAP[fieldType] ?? "TEXT";
  const quotedTable = quoteIdentifier(entityName);
  const quotedField = quoteIdentifier(fieldName);
  const literalField = quoteLiteral(fieldName);

  // Build column definition
  let columnDef = `${quotedField} ${sqlType}`;
  if (config.required) {
    // Use a default for the NOT NULL constraint during backfill
    const defaultExpr = getDefaultExpression(fieldType, config);
    if (defaultExpr !== null) {
      columnDef += ` NOT NULL DEFAULT ${defaultExpr}`;
    }
  }

  const lines: string[] = [
    `-- Promote overlay field ${literalField} on entity ${quotedTable}`,
    `-- Generated by: linch overlay promote`,
    "",
    `-- Step 1: Add the real column`,
    `ALTER TABLE ${quotedTable} ADD COLUMN ${columnDef};`,
    "",
    `-- Step 2: Backfill from _extensions JSONB`,
  ];

  // For JSON type, no cast needed — just extract the JSON value
  if (fieldType === "json") {
    if (config.required) {
      const fallback = getDefaultExpression(fieldType, config) ?? "'null'::jsonb";
      lines.push(
        `UPDATE ${quotedTable}`,
        `SET ${quotedField} = COALESCE(_extensions->${literalField}, ${fallback})`,
        `WHERE _extensions ? ${literalField};`,
      );
    } else {
      lines.push(
        `UPDATE ${quotedTable}`,
        `SET ${quotedField} = _extensions->${literalField}`,
        `WHERE _extensions ? ${literalField};`,
      );
    }
  } else {
    if (config.required) {
      const fallback = getDefaultExpression(fieldType, config) ?? `''`;
      lines.push(
        `UPDATE ${quotedTable}`,
        `SET ${quotedField} = COALESCE((_extensions->>${literalField})::${castType}, ${fallback})`,
        `WHERE _extensions ? ${literalField};`,
      );
    } else {
      lines.push(
        `UPDATE ${quotedTable}`,
        `SET ${quotedField} = (_extensions->>${literalField})::${castType}`,
        `WHERE _extensions ? ${literalField};`,
      );
    }
  }

  lines.push(
    "",
    `-- Step 3: Clean up _extensions (remove promoted key)`,
    `UPDATE ${quotedTable}`,
    `SET _extensions = _extensions - ${literalField}`,
    `WHERE _extensions ? ${literalField};`,
  );

  return lines.join("\n");
}

/**
 * Generate a complete promotion plan for an overlay field.
 */
export function generatePromotionPlan(overlay: FieldOverlayRecord): PromotionPlan {
  return {
    entityName: overlay.entityName,
    fieldName: overlay.fieldName,
    overlay,
    fieldDefinitionCode: generateFieldCode(overlay),
    migrationSql: generateMigrationSql(overlay.entityName, overlay),
  };
}

/** Get a SQL default expression for a field type, used when column is NOT NULL */
function getDefaultExpression(fieldType: string, config: OverlayFieldConfig): string | null {
  if (config.defaultValue !== undefined) {
    if (typeof config.defaultValue === "string") {
      return quoteLiteral(config.defaultValue);
    }
    if (typeof config.defaultValue === "number") {
      return String(config.defaultValue);
    }
    if (typeof config.defaultValue === "boolean") {
      return config.defaultValue ? "TRUE" : "FALSE";
    }
    return quoteLiteral(JSON.stringify(config.defaultValue));
  }

  // Provide sensible zero-value defaults for required fields
  switch (fieldType) {
    case "string":
    case "enum":
      return "''";
    case "number":
      return "0";
    case "boolean":
      return "FALSE";
    case "date":
      return "'epoch'::timestamptz";
    case "json":
      return "'null'::jsonb";
    default:
      return null;
  }
}
