/**
 * Action Helpers
 *
 * Pure utility functions for action execution pipeline.
 * Extracted from action-engine.ts for maintainability.
 */

import { generateZodSchema } from "../entity/entity-to-zod";
import type {
  ActionContext,
  ActionDefinition,
  ActionExposure,
  Actor,
  ValidationResult,
} from "../types/action";
import type { EntityDefinition, FieldDefinition, LockCondition } from "../types/entity";
import type { ExecutionMeta } from "../types/execution-meta";
import { extendExecutionMeta } from "../types/execution-meta";
import type { ExecutionChannel } from "./action-engine-types";
import { checkFieldLocks, type FieldLockViolation } from "./field-lock-checker";
import type { InterceptorRegistry } from "./interceptors";

// NOTE: Group-based permission enforcement lives exclusively in cap-permission
// via the CommandLayer "permission" slot — the executor no longer performs any
// group check (Spec 10 §7.8: open-by-default when cap-permission is absent).
//
// Actor-type filtering (`permissions.actorTypes`) is a different concern: it's
// a first-order authorization gate declared on the action itself (e.g. a
// system-only dispatch primitive, an AI-only tool). Spec 10 requires it to be
// enforced on every execution path, so the executor keeps this check. See
// `checkActorType` below.

/**
 * Resolve a `$`-prefixed expression in declarative `setFields`.
 *
 * Supported:
 * - `$actor.id`, `$actor.name`, `$actor.type` — current actor fields
 * - `$input.<field>` — action input fields
 * - `$now` — current ISO timestamp
 * - `$now.date` — current ISO date (YYYY-MM-DD)
 * - Plain values pass through unchanged.
 */
export function resolveFieldExpression(
  value: unknown,
  input: Record<string, unknown>,
  actor: Actor,
): unknown {
  if (typeof value !== "string" || !value.startsWith("$")) return value;

  if (value === "$now") return new Date().toISOString();
  if (value === "$now.date") return new Date().toISOString().slice(0, 10);

  if (value.startsWith("$actor.")) {
    const field = value.slice("$actor.".length);
    return (actor as unknown as Record<string, unknown>)[field];
  }

  if (value.startsWith("$input.")) {
    const field = value.slice("$input.".length);
    return input[field];
  }

  // Unknown expression — return as-is
  return value;
}

export function generateExecutionId(): string {
  return `exec_${crypto.randomUUID()}`;
}

/**
 * Enforce `permissions.actorTypes` — the only authorization field still owned
 * by the Action Engine after issue #125. Returns an error string (for logging
 * + response) or `null` when the actor type is allowed.
 *
 * Group-based checks live in the CommandLayer "permission" slot; this one
 * stays here because it's declared on the action itself and must hold for
 * every entry point (REST, GraphQL, MCP, internal execute), not just the
 * pipeline-aware callers.
 */
export function checkActorType(action: ActionDefinition, actor: Actor): string | null {
  const allowed = action.permissions?.actorTypes;
  if (!allowed || allowed.length === 0) return null;
  if (!allowed.includes(actor.type)) {
    return `Actor type "${actor.type}" is not allowed for action "${action.name}"`;
  }
  return null;
}

/** Check if the action is exposed for the given channel */
export function isExposed(
  exposure: ActionExposure | "all" | undefined,
  channel: ExecutionChannel,
): boolean {
  // Default: all channels allowed
  if (exposure === undefined || exposure === "all") {
    return true;
  }

  const mapping: Record<ExecutionChannel, keyof ActionExposure> = {
    http: "http",
    mcp: "mcp",
    cli: "cli",
    ui: "ui",
    internal: "internal",
  };

  const key = mapping[channel];
  // If not explicitly set, default to true
  return exposure[key] !== false;
}

/** Options for {@link validateInput}. */
export interface ValidateInputOptions {
  /**
   * When true (production/staging), validate action input against a Zod schema
   * generated from the action's `input` field definitions — checking types and
   * constraints, not just required-field presence. Defaults to false so dev/test
   * stay lenient with toy inputs. See {@link ActionExecutorOptions.strictValidation}.
   */
  strict?: boolean;
}

/**
 * Validate action input.
 *
 * Always runs the required-field-presence check first (the historical, lenient
 * behaviour). When `strict` is enabled AND the action declares an `input`, it
 * additionally validates each value's TYPE and CONSTRAINTS via a Zod schema
 * generated by {@link generateZodSchema}.
 *
 * Non-breaking guarantee: strict validation must reject clearly-wrong inputs
 * (wrong primitive type, bad enum, missing required) but must NEVER reject a
 * value the lenient path would have accepted from a real HTTP/GraphQL client.
 * This holds because `generateZodSchema` maps each field type to its on-the-wire
 * shape — `date`/`datetime` → `z.string()` (clients send ISO strings, never
 * `Date` objects across JSON), `json` → `z.unknown()` (any shape passes), and
 * `z.object` STRIPS unknown keys by default (extra fields never trigger a
 * rejection). The generator also honours each field's own `required` flag
 * (optional fields become `nullable().optional()`), so CRUD update actions —
 * whose generator marks input fields optional — are not over-tightened.
 */
export function validateInput(
  action: ActionDefinition,
  input: Record<string, unknown>,
  options?: ValidateInputOptions,
): ValidationResult {
  // Check required fields from input definition (lenient path — always runs).
  if (action.input) {
    const errors: Array<{ field: string; message: string }> = [];
    for (const [fieldName, fieldDef] of Object.entries(action.input)) {
      if (fieldDef.required && (input[fieldName] === undefined || input[fieldName] === null)) {
        errors.push({ field: fieldName, message: `Field "${fieldName}" is required` });
      }
    }
    if (errors.length > 0) {
      return { valid: false, errors };
    }
  }

  // Strict, type-aware validation — opt-in via `strict` (production/staging).
  if (options?.strict && action.input) {
    // Synthesize an entity-shaped argument for the shared schema generator.
    // `name` and `fields` are the only required EntityDefinition members; the
    // action's input field defs are the SAME FieldDefinition type entity fields
    // use, so this is structurally valid without any cast hacks.
    const entityShape: EntityDefinition = {
      name: action.entity ?? action.name,
      fields: action.input,
    };

    // `includeSystemFields` keeps server-managed identifiers (id, tenant_id, …)
    // that the executor reads from input (e.g. the update record id) — they are
    // validated as optional and NOT stripped — while genuinely undeclared keys
    // are removed from the parsed payload.
    const result = generateZodSchema(entityShape, { includeSystemFields: true }).safeParse(input);
    if (!result.success) {
      const errors = result.error.issues.map((issue) => ({
        field: issue.path.length > 0 ? issue.path.join(".") : "(root)",
        message: issue.message,
      }));
      return { valid: false, errors };
    }
    // Return the sanitized (allowlisted) payload so the executor forwards only
    // declared + system keys to handlers — undeclared keys never reach the write
    // path. `z.object` strips unknown keys by default, so `result.data` is the
    // input minus anything not in the schema.
    return { valid: true, value: result.data };
  }

  return { valid: true };
}

/** Run pre-validation (validate.required on the record, validate.custom) */
export function runPreValidation(action: ActionDefinition, ctx: ActionContext): ValidationResult {
  if (!action.validate) {
    return { valid: true };
  }

  // validate.required checks fields on the input
  if (action.validate.required && action.validate.required.length > 0) {
    const errors: Array<{ field: string; message: string }> = [];
    for (const field of action.validate.required) {
      if (ctx.input[field] === undefined || ctx.input[field] === null || ctx.input[field] === "") {
        errors.push({ field, message: `Field "${field}" is required` });
      }
    }
    if (errors.length > 0) {
      return { valid: false, errors };
    }
  }

  // validate.custom — wrap in try/catch so exceptions don't escape
  if (action.validate.custom) {
    try {
      return action.validate.custom(ctx);
    } catch (err) {
      return {
        valid: false,
        errors: [
          {
            field: "_custom",
            message: err instanceof Error ? err.message : String(err),
          },
        ],
      };
    }
  }

  return { valid: true };
}

/**
 * Duck-type check: does `value` look like an {@link ExecutionMeta}? The
 * public ExecuteOptions.meta accepts either a pre-built ExecutionMeta (how
 * the CommandLayer + nested ctx.execute pass it) or a plain record (natural
 * external call shape). We detect the former by the presence of the typed
 * accessor methods rather than an `instanceof` check so third-party
 * implementations (e.g., future Phase 2 subclasses) still work.
 */
export function isExecutionMeta(value: unknown): value is ExecutionMeta {
  if (value === null || typeof value !== "object") return false;
  const candidate = value as Record<string, unknown>;
  return (
    typeof candidate.get === "function" &&
    typeof candidate.has === "function" &&
    typeof candidate.require === "function" &&
    typeof candidate.toJSON === "function"
  );
}

/**
 * Extend an incoming ExecutionMeta with system defaults ONLY for keys the
 * parent has not already set. Prevents a child execution from clobbering
 * root-level `_execution_id`, while still backfilling it when a parent meta
 * happens to arrive without one.
 */
export function fillMissingSystemKeys(
  meta: ExecutionMeta,
  systemDefaults: Record<string, unknown>,
): ExecutionMeta {
  const missing: Record<string, unknown> = {};
  for (const [k, v] of Object.entries(systemDefaults)) {
    if (!meta.has(k)) missing[k] = v;
  }
  if (Object.keys(missing).length === 0) return meta;
  return extendExecutionMeta(meta, {}, missing);
}

/**
 * Run the field-lock check and thread the resulting violations through the
 * `field-lock-check` interceptor point (Spec 63 Phase 3), returning the
 * (possibly transformed) violation set.
 *
 * Both update paths — the `ctx.update()` handler wrapper and the declarative
 * `setFields` / `stateTransition` path — share this exact sequence; extracting
 * it keeps them byte-for-byte identical. The interceptor step is an identity
 * when no `field-lock-check` interceptor is registered, so behavior is
 * unchanged from Phase 1 in that case.
 */
export async function checkAndRunFieldLockInterceptor(opts: {
  entity: string;
  fields: Record<string, FieldDefinition>;
  lockAllWhen: LockCondition | undefined;
  lockAllowFields: string[] | undefined;
  existingRecord: Record<string, unknown>;
  writesToCheck: Record<string, unknown>;
  actor: Actor;
  tenantId?: string;
  interceptorRegistry?: InterceptorRegistry;
}): Promise<FieldLockViolation[]> {
  const {
    entity,
    fields,
    lockAllWhen,
    lockAllowFields,
    existingRecord,
    writesToCheck,
    actor,
    tenantId,
    interceptorRegistry,
  } = opts;
  let violations = checkFieldLocks({
    fields,
    lockAllWhen,
    lockAllowFields,
    existingRecord,
    input: writesToCheck,
  });
  // Spec 63 Phase 3: let a policy capability transform the violation set
  // (shadow / bypass / tolerance). Identity when no interceptor is registered.
  if (interceptorRegistry?.has("field-lock-check")) {
    violations = await interceptorRegistry.run("field-lock-check", violations, {
      entity,
      actor,
      record: existingRecord,
      input: writesToCheck,
      tenantId,
    });
  }
  return violations;
}
