/**
 * Generate .linchkit/drizzle-schema.generated.ts
 *
 * Serializes SchemaDefinition[] → pgTable → .ts source file.
 * This is the single bridge between LinchKit's capability-based schema
 * definitions and drizzle-kit's requirement for static .ts schema files.
 *
 * Used by: linch dev, linch db:generate, linch db:push, integration tests.
 */

import { existsSync, mkdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { getTableConfig } from "drizzle-orm/pg-core";
import type { SchemaDefinition } from "../types/schema";
import { generateDrizzleTable } from "./schema-to-drizzle";

const DEFAULT_OUTPUT_DIR = ".linchkit";
const DEFAULT_OUTPUT_FILE = "drizzle-schema.generated.ts";

// SQL type → drizzle-orm/pg-core builder function mapping
const SQL_TYPE_MAP: Record<string, (name: string) => string> = {
  text: (n) => `text("${n}")`,
  boolean: (n) => `boolean("${n}")`,
  integer: (n) => `integer("${n}")`,
  numeric: (n) => `numeric("${n}")`,
  "double precision": (n) => `numeric("${n}")`,
  bigint: (n) => `integer("${n}")`,
  jsonb: (n) => `jsonb("${n}")`,
  date: (n) => `date("${n}")`,
  timestamp: (n) => `timestamp("${n}")`,
  uuid: (n) => `text("${n}")`,
};

export interface GenerateSchemaFileOptions {
  /** Output directory name relative to projectRoot (default: ".linchkit") */
  outputDir?: string;
  /** Output filename (default: "drizzle-schema.generated.ts") */
  outputFile?: string;
}

/**
 * Generate a Drizzle schema barrel file from SchemaDefinitions.
 * Returns the absolute path to the generated file.
 */
export function generateDrizzleSchemaFile(
  schemas: SchemaDefinition[],
  projectRoot: string = process.cwd(),
  options?: GenerateSchemaFileOptions,
): string {
  const outDir = join(projectRoot, options?.outputDir ?? DEFAULT_OUTPUT_DIR);
  const outPath = join(outDir, options?.outputFile ?? DEFAULT_OUTPUT_FILE);

  if (!existsSync(outDir)) {
    mkdirSync(outDir, { recursive: true });
  }

  const tableExports: string[] = [];

  for (const schema of schemas) {
    const table = generateDrizzleTable(schema);
    const config = getTableConfig(table);
    const varName = toCamelCase(schema.name) + "Table";

    const columnDefs = config.columns.map((col) => {
      const code = serializeColumn(col as never);
      return `  ${col.name}: ${code}`;
    });

    tableExports.push(
      `export const ${varName} = pgTable("${config.name}", {\n${columnDefs.join(",\n")}\n});`,
    );
  }

  const content = `// Auto-generated by linch CLI — do not edit manually
// Regenerated on every \`linch dev\` / \`linch db:generate\`
import { boolean, date, integer, jsonb, numeric, pgTable, text, timestamp, varchar } from "drizzle-orm/pg-core";

// System tables
export {
  approvalsTable,
  approvalStatusEnum,
  eventsTable,
  eventStatusEnum,
  executionsTable,
  executionStatusEnum,
} from "@linchkit/core/server";

// Capability tables
${tableExports.join("\n\n")}
`;

  writeFileSync(outPath, content, "utf-8");
  return outPath;
}

/**
 * Serialize a Drizzle column object to its TS code representation.
 *
 * Uses getSQLType() to determine the column's SQL type, then maps back to
 * the drizzle-orm builder function. This avoids duplicating the field-type
 * mapping logic from schema-to-drizzle.ts — we read what Drizzle already
 * computed rather than re-computing from SchemaDefinition.
 *
 * Known limitations (harmless for current architecture since generated file
 * is only consumed by drizzle-kit for DDL, not for runtime queries):
 * - timestamp({ mode: "date" }) → serialized as timestamp() (mode lost, DDL identical)
 * - defaultRandom() / gen_random_uuid() → not serialized (capability tables use app-generated IDs)
 * - Table-level indexes → not serialized (system table indexes are re-exported directly)
 * - pgEnum types → not serialized (capability tables use varchar for enums)
 */
function serializeColumn(col: {
  name: string;
  dataType: string;
  notNull: boolean;
  hasDefault: boolean;
  default?: unknown;
  defaultFn?: unknown;
  primary: boolean;
  isUnique: boolean;
  getSQLType: () => string;
}): string {
  const sqlType = col.getSQLType();

  // Match against known SQL types; varchar(N) needs special handling
  let code: string;
  const varcharMatch = sqlType.match(/^varchar\((\d+)\)$/);
  if (varcharMatch) {
    code = `varchar("${col.name}", { length: ${varcharMatch[1]} })`;
  } else {
    const builder = SQL_TYPE_MAP[sqlType];
    if (!builder) {
      console.warn(`[generate-drizzle-schema] Unknown SQL type "${sqlType}" for column "${col.name}", falling back to text`);
    }
    code = builder ? builder(col.name) : `text("${col.name}")`;
  }

  // Apply modifiers in the same order as schema-to-drizzle.ts
  if (col.primary) code += ".primaryKey()";
  if (col.hasDefault) {
    const def = col.default;
    if (isSqlDefault(def)) {
      // SQL-based defaults: detect now() for .defaultNow()
      const sqlStr = extractSqlString(def);
      if (sqlStr === "now()") {
        code += ".defaultNow()";
      }
      // Other SQL defaults (gen_random_uuid, etc.) — skip, drizzle-kit will introspect
    } else if (col.defaultFn) {
      // Function-based defaults
      if (col.dataType === "date") code += ".defaultNow()";
    } else if (def !== undefined && def !== null) {
      // Scalar defaults
      code += `.default(${JSON.stringify(def)})`;
    }
  }
  if (col.notNull) code += ".notNull()";
  if (col.isUnique) code += ".unique()";

  return code;
}

/** Convert snake_case/kebab-case to camelCase */
function toCamelCase(name: string): string {
  return name
    .split(/[_-]/)
    .map((part, i) => (i === 0 ? part : part.charAt(0).toUpperCase() + part.slice(1)))
    .join("");
}

/** Check if a default value is a Drizzle SQL object */
function isSqlDefault(def: unknown): boolean {
  return typeof def === "object" && def !== null && "queryChunks" in def;
}

/**
 * Extract the SQL string from a Drizzle SQL default (e.g. sql`now()` → "now()").
 * NOTE: This reaches into drizzle-orm's internal queryChunks structure, which is
 * not part of the public API and may change between versions. Pinned to drizzle-orm >=0.45.
 */
function extractSqlString(def: unknown): string | null {
  try {
    const chunks = (def as { queryChunks: Array<{ value: string[] }> }).queryChunks;
    if (chunks?.length === 1 && chunks[0]?.value?.length === 1) {
      return chunks[0].value[0] ?? null;
    }
  } catch {
    // Not a recognizable SQL structure
  }
  return null;
}
