/**
 * ProposalFileWriter — Spec 55 §7.6 "Graduation: from data to code".
 *
 * Persists the changes carried by an approved Proposal as TypeScript source
 * files under the target capability's tree. Once written, the developer can
 * review the diff in source control, run their build, and ship — closing the
 * human-in-the-loop hand-off between Memory-resident proposals and Layer 0
 * (Git) source-of-truth.
 *
 * This is intentionally a thin writer:
 *   - No Prettier round-trip (the developer formats on save / in CI).
 *   - No Git commit (delegated to the caller — could be a PR, a hot-reload, etc.).
 *   - No template inheritance (each change kind gets a small, predictable stub).
 *
 * The default behaviour assumes the standard `addons/<group>/cap-<short>/src/...`
 * layout. Consumers can override path resolution and codegen via the options
 * if their capability lives elsewhere or carries an unusual ChangeDefinition.
 */

import { existsSync } from "node:fs";
import { mkdir, readdir, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import type { Logger } from "../types/logger";
import type { ProposalChange, ProposalChangeTarget, ProposalDefinition } from "../types/proposal";

// ── Options ─────────────────────────────────────────────────

export interface ProposalFileWriterOptions {
  /** Absolute path to the repository root — used to resolve `addons/<group>/cap-<short>/src/...`. */
  rootDir: string;
  /** Optional logger (defaults to a console-prefixed shim). */
  logger?: Logger;
  /** Override the resolved path per change. Returns an absolute path. */
  pathResolver?: (proposal: ProposalDefinition, change: ProposalChange) => string;
  /** Custom code generator (escape hatch for unusual ChangeDefinition shapes). */
  codegen?: (proposal: ProposalDefinition, change: ProposalChange) => string;
}

// ── Defaults ────────────────────────────────────────────────

/** Map a change target to its subdirectory (relative to `<cap>/src/`). */
const TARGET_SUBDIR: Record<ProposalChangeTarget, string> = {
  entity: "entities",
  action: "actions",
  rule: "rules",
  view: "views",
  state: "states",
  event: "events",
  flow: "flows",
  overlay: "overlays",
};

/** Map a change target to its file-name discriminator. */
const TARGET_KIND_SUFFIX: Record<ProposalChangeTarget, string> = {
  entity: "entity",
  action: "action",
  rule: "rule",
  view: "view",
  state: "state",
  event: "event",
  flow: "flow",
  overlay: "overlay",
};

/** Map a change target to its `defineXxx` factory name. */
const TARGET_FACTORY: Record<ProposalChangeTarget, string> = {
  entity: "defineEntity",
  action: "defineAction",
  rule: "defineRule",
  view: "defineView",
  state: "defineState",
  event: "defineEvent",
  flow: "defineFlow",
  overlay: "defineOverlay",
};

/**
 * Normalise the proposal's `capability` field into the cap-prefixed directory
 * name we expect under `addons/<group>/`. The proposal stores it either as
 * `"cap-life-demo"` (already prefixed) or `"life_demo"` / `"life-demo"`
 * (bare). We always emit the `cap-…` form.
 */
function normaliseCapName(capability: string): string {
  if (capability.startsWith("cap-")) return capability;
  // snake_case → kebab-case so the on-disk folder name is consistent.
  return `cap-${capability.replace(/_/g, "-")}`;
}

/**
 * Best-effort lookup of the `<group>` segment in `addons/<group>/cap-<short>/`.
 *
 * The proposal does not carry the group name (Capabilities are addressed by
 * their `cap-*` name only). We scan `addons/` once and find the first child
 * directory that contains `cap-<short>`. If none is found we fall back to
 * `<short minus 'cap-'>` which matches the convention used by single-member
 * groups (e.g. `addons/permission/cap-permission/`).
 */
async function resolveCapGroup(rootDir: string, capName: string): Promise<string> {
  const addonsRoot = join(rootDir, "addons");
  if (!existsSync(addonsRoot)) {
    return capName.replace(/^cap-/, "");
  }
  try {
    const groups = await readdir(addonsRoot, { withFileTypes: true });
    for (const entry of groups) {
      if (!entry.isDirectory()) continue;
      const candidate = join(addonsRoot, entry.name, capName);
      if (existsSync(candidate)) return entry.name;
    }
  } catch {
    // fall through to default
  }
  return capName.replace(/^cap-/, "");
}

/** Build a default header comment for a generated file. */
function buildHeader(proposal: ProposalDefinition, change: ProposalChange): string {
  const now = new Date().toISOString();
  return [
    "/**",
    " * AUTO-GENERATED by ProposalFileWriter (Spec 55 §7.6).",
    " *",
    ` * Sourced from Proposal: ${proposal.id}`,
    ` * Title:                 ${proposal.title}`,
    ` * Capability:            ${proposal.capability}`,
    ` * Change target:         ${change.target} (${change.operation})`,
    ` * Generated at:          ${now}`,
    " *",
    " * Review the diff in source control. Edit freely — this file is intended",
    " * to be the persistent, human-curated form of the proposed change.",
    " */",
    "",
  ].join("\n");
}

/** Default codegen: import the matching `defineXxx` and re-emit the change. */
function defaultCodegen(proposal: ProposalDefinition, change: ProposalChange): string {
  const factory = TARGET_FACTORY[change.target];
  const definition = change.definition ?? { name: change.name };
  const header = buildHeader(proposal, change);

  // Use JSON.stringify with `null, 2` for the "frozen-at-write-time" shape.
  // Functions / Dates inside ChangeDefinition will be lost — that's by design;
  // the developer is expected to massage anything dynamic in-source.
  const serialized = JSON.stringify(definition, null, 2);

  return `${header}import { ${factory} } from "@linchkit/core";\n\nexport default ${factory}(${serialized});\n`;
}

// ── ProposalFileWriter ──────────────────────────────────────

export class ProposalFileWriter {
  private readonly rootDir: string;
  private readonly logger?: Logger;
  private readonly pathResolver?: (proposal: ProposalDefinition, change: ProposalChange) => string;
  private readonly codegen: (proposal: ProposalDefinition, change: ProposalChange) => string;

  constructor(options: ProposalFileWriterOptions) {
    this.rootDir = options.rootDir;
    this.logger = options.logger;
    this.pathResolver = options.pathResolver;
    this.codegen = options.codegen ?? defaultCodegen;
  }

  /**
   * Write every change in an approved proposal to disk.
   *
   * Throws if `proposal.status !== "approved"` (defensive — the writer is
   * only meant to be invoked from the approval hook, never directly).
   *
   * For each change:
   *   - Resolves the target path (`pathResolver` or default layout).
   *   - Generates TypeScript source (`codegen` or default factory wrap).
   *   - Creates any missing parent directories.
   *   - Refuses to overwrite an existing file when `change.operation === "create"`.
   *   - Allows overwrite when `change.operation === "update"`.
   *   - Delete operations are intentionally skipped — deleting a Capability's
   *     source file is too destructive to do silently from an approval hook.
   *
   * Returns the list of absolute paths actually written.
   */
  async writeApprovedProposal(proposal: ProposalDefinition): Promise<string[]> {
    if (proposal.status !== "approved") {
      throw new Error(
        `ProposalFileWriter requires status "approved" — got "${proposal.status}" for proposal "${proposal.id}"`,
      );
    }

    const written: string[] = [];
    for (const change of proposal.changes) {
      if (change.operation === "delete") {
        this.logger?.warn?.(
          `ProposalFileWriter: skipping delete operation for "${change.name}" — manual removal required`,
          { proposalId: proposal.id, target: change.target, name: change.name },
        );
        continue;
      }

      const targetPath = await this.resolvePath(proposal, change);

      if (change.operation === "create" && existsSync(targetPath)) {
        throw new Error(
          `ProposalFileWriter: refusing to overwrite existing file at "${targetPath}" ` +
            `(proposal "${proposal.id}" change "${change.name}" is a create operation). ` +
            `If this is an intentional rewrite, change operation to "update".`,
        );
      }

      const source = this.codegen(proposal, change);
      await mkdir(dirname(targetPath), { recursive: true });
      await writeFile(targetPath, source, "utf8");
      this.logger?.info?.(`ProposalFileWriter: wrote ${targetPath}`, {
        proposalId: proposal.id,
        target: change.target,
        name: change.name,
        operation: change.operation,
      });
      written.push(targetPath);
    }

    return written;
  }

  /** Resolve the absolute write path for a change. */
  private async resolvePath(proposal: ProposalDefinition, change: ProposalChange): Promise<string> {
    if (this.pathResolver) return this.pathResolver(proposal, change);

    const capName = normaliseCapName(proposal.capability);
    const group = await resolveCapGroup(this.rootDir, capName);
    const subdir = TARGET_SUBDIR[change.target];
    const kindSuffix = TARGET_KIND_SUFFIX[change.target];
    const filename = `_${proposal.id}.${kindSuffix}.ts`;
    return join(this.rootDir, "addons", group, capName, "src", subdir, filename);
  }
}
